/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CafeRouteImport } from './routes/cafe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'

const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeRoute = CafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cafe': typeof CafeRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/story': typeof StoryRoute
  '/subscribe': typeof SubscribeRoute
  '/wholesale': typeof WholesaleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cafe': typeof CafeRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRouteWithChildren
  '/story': typeof StoryRoute
  '/subscribe': typeof SubscribeRoute
  '/wholesale': typeof WholesaleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cafe': typeof CafeRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/story': typeof StoryRoute
  '/subscribe': typeof SubscribeRoute
  '/wholesale': typeof WholesaleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cafe'
    | '/careers'
    | '/cart'
    | '/contact'
    | '/journal'
    | '/shop'
    | '/story'
    | '/subscribe'
    | '/wholesale'
    | '/journal/$slug'
    | '/shop/$slug'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cafe'
    | '/careers'
    | '/cart'
    | '/contact'
    | '/journal'
    | '/story'
    | '/subscribe'
    | '/wholesale'
    | '/journal/$slug'
    | '/shop/$slug'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/cafe'
    | '/careers'
    | '/cart'
    | '/contact'
    | '/journal'
    | '/shop'
    | '/story'
    | '/subscribe'
    | '/wholesale'
    | '/journal/$slug'
    | '/shop/$slug'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CafeRoute: typeof CafeRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  JournalRoute: typeof JournalRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  StoryRoute: typeof StoryRoute
  SubscribeRoute: typeof SubscribeRoute
  WholesaleRoute: typeof WholesaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe': {
      id: '/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
  }
}

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CafeRoute: CafeRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  JournalRoute: JournalRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  StoryRoute: StoryRoute,
  SubscribeRoute: SubscribeRoute,
  WholesaleRoute: WholesaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
